name: websockets-release
on:
  push:
    branches:
      - main
    paths:
      - websockets/**
      - "!websockets/package-lock.json"
jobs:
  build-websockets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: websockets
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
      - name: Install winglang
        run: npm i -g winglang
      - name: Install dependencies
        run: npm install --include=dev
        working-directory: websockets
      - name: Test
        run: wing test
        working-directory: websockets
      - name: Automated version bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          PACKAGEJSON_DIR: websockets
        with:
          minor-wording: add,Adds,new
          major-wording: MAJOR,cut-major
          patch-wording: patch,fixes
          rc-wording: RELEASE,alpha
      - name: Pack
        run: wing pack
        working-directory: websockets
      - name: Get package version
        run: echo WINGLIB_VERSION=$(node -p "require('./package.json').version") >>
          "$GITHUB_ENV"
        working-directory: websockets
      - name: Publish
        run: npm publish --access=public --registry https://registry.npmjs.org --tag
          latest *.tgz
        working-directory: websockets
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          tag: websockets-v${{ env.WINGLIB_VERSION }}
      - name: GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: websockets v${{ env.WINGLIB_VERSION }}
          tag_name: websockets-v${{ env.WINGLIB_VERSION }}
          files: "*.tgz"
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
